setting initial sound source origin:  True
Individualiser Running!
the host is:  ec2-35-176-144-147.eu-west-2.compute.amazonaws.com
Traceback (most recent call last):
  File "__main__.py", line 98, in <module>
    main()
  File "__main__.py", line 45, in main
    sock_in.bind((host, in_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
setting initial sound source origin:  True
Individualiser Running!
the host is:  ec2-35-176-144-147.eu-west-2.compute.amazonaws.com
Traceback (most recent call last):
  File "__main__.py", line 98, in <module>
    main()
  File "__main__.py", line 45, in main
    sock_in.bind((host, in_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
setting initial sound source origin:  True
Individualiser Running!
the host is:  ec2-35-176-144-147.eu-west-2.compute.amazonaws.com
Traceback (most recent call last):
  File "__main__.py", line 98, in <module>
    main()
  File "__main__.py", line 45, in main
    sock_in.bind((host, in_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
